//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-09/06/2010 03:32 PM(foreman)-fcs)
//


package com.siebel.xml.aabr_20bankmail_20response_20io;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccessGrant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessGrant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SBTACCESSID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessGrant", namespace = "http://www.siebel.com/xml/AABR%20Bankmail%20Response%20IO", propOrder = {
    "sbtaccessid"
})
public class AccessGrant {

    @XmlElement(name = "SBTACCESSID")
    protected String sbtaccessid;

    /**
     * Gets the value of the sbtaccessid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSBTACCESSID() {
        return sbtaccessid;
    }

    /**
     * Sets the value of the sbtaccessid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSBTACCESSID(String value) {
        this.sbtaccessid = value;
    }

}
