//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-09/06/2010 03:32 PM(foreman)-fcs)
//


package com.siebel.xml.aabr_20bankmail_20response_20io;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.siebel.xml.aabr_20bankmail_20response_20io package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListOfBankmailResponse_QNAME = new QName("http://www.siebel.com/xml/AABR%20Bankmail%20Response%20IO", "ListOfBankmailResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.siebel.xml.aabr_20bankmail_20response_20io
     * 
     */
    public ObjectFactory() {
    	//empty constructor
    }

    /**
     * Create an instance of {@link ListOfBankmailResponseTopElmt }
     * @return ListOfBankmailResponseTopElmt ListOfBankmailResponseTopElmt
     */
    public ListOfBankmailResponseTopElmt createListOfBankmailResponseTopElmt() {
        return new ListOfBankmailResponseTopElmt();
    }

    /**
     * Create an instance of {@link ListOfBankmailResponse }
     * @return ListOfBankmailResponse ListOfBankmailResponse
     */
    public ListOfBankmailResponse createListOfBankmailResponse() {
        return new ListOfBankmailResponse();
    }

    /**
     * Create an instance of {@link AccessGrant }
     * @return AccessGrant AccessGrant
     */
    public AccessGrant createAccessGrant() {
        return new AccessGrant();
    }

    /**
     * Create an instance of {@link Users }
     * @return Users users
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link ReturnCodes }
     * @return ReturnCodes ReturnCodes
     */
    public ReturnCodes createReturnCodes() {
        return new ReturnCodes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfBankmailResponse }{@code >}}
     * @return JAXBElement<ListOfBankmailResponse> JAXBElement<ListOfBankmailResponse>
     */
    @XmlElementDecl(namespace = "http://www.siebel.com/xml/AABR%20Bankmail%20Response%20IO", name = "ListOfBankmailResponse")
    public JAXBElement<ListOfBankmailResponse> createListOfBankmailResponse(ListOfBankmailResponse value) {
        return new JAXBElement<ListOfBankmailResponse>(_ListOfBankmailResponse_QNAME, ListOfBankmailResponse.class, null, value);
    }

}
