//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-09/06/2010 03:32 PM(foreman)-fcs)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.siebel.com/xml/AABR%20Bankmail%20Response%20IO", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.siebel.xml.aabr_20bankmail_20response_20io;
