//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-09/06/2010 03:32 PM(foreman)-fcs)
//


package com.siebel.customui;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.abnamro.nl.logging.log4j2.helper.LogHelper;
/**
 * AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF
 *
 * <PRE>
 * &lt;B&gt;History:&lt;/B&gt;
 * Developer          Date       Change Reason	  Change
 * ------------------ ---------- ----------------- ----------------------------------------------
 * TCS			  	01-11-2012	Initial version	  Release 1.0
 * </PRE>
 *
 * @author
 * @see
 */
@WebServiceClient(name = "AAB_spcBankmail_spcCal_spcAccess_spcInbound_spcWF", targetNamespace = "http://siebel.com/CustomUI", wsdlLocation = "META-INF/wsdl/CRM_BankmailAccess.wsdl")
public class AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF
    extends Service
{
	/**
	 * Singleton instance of LogHelper.
	 */
	private static final LogHelper LOGGER = new LogHelper(AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF.class);

    private final static URL AABSPCBANKMAILSPCCALSPCACCESSSPCINBOUNDSPCWF_WSDL_LOCATION;
    private final static String LOG_METHOD = "AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF(HttpServletRequest, HttpServletResponse, String):Response";

    static {
        URL url = null;
        try {
            url = com.siebel.customui.AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF.class.getResource("/META-INF/wsdl/CRM_BankmailAccess.wsdl");
            if (url == null) {throw new MalformedURLException("/META-INF/wsdl/CRM_BankmailAccess.wsdl does not exist in the module.");}
        } catch (MalformedURLException e) {
        	LOGGER.error(LOG_METHOD, "Malformed URL exception",e);            
        }
        AABSPCBANKMAILSPCCALSPCACCESSSPCINBOUNDSPCWF_WSDL_LOCATION = url;
    }

    /**
     * Constructor for AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF
     * @param wsdlLocation URL
     * @param serviceName QName
     */
    public AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Constructor for AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF
     */
    public AABSpcBankmailSpcCalSpcAccessSpcInboundSpcWF() {
        super(AABSPCBANKMAILSPCCALSPCACCESSSPCINBOUNDSPCWF_WSDL_LOCATION, new QName("http://siebel.com/CustomUI", "AAB_spcBankmail_spcCal_spcAccess_spcInbound_spcWF"));
    }

    /**
     * 
     * @return
     *     returns BankmailAccess
     */
    @WebEndpoint(name = "BankmailAccess")
    public BankmailAccess getBankmailAccess() {
        return (BankmailAccess)super.getPort(new QName("http://siebel.com/CustomUI", "BankmailAccess"), BankmailAccess.class);
    }

}
