//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-09/06/2010 03:32 PM(foreman)-fcs)
//


package com.siebel.customui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.siebel.xml.aabr_20bankmail_20calendar_20io_ext.ListOfAabrBankmailCalendarIoExt;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.siebel.com/xml/AABR%20Bankmail%20Calendar%20IO_Ext}ListOfAabrBankmailCalendarIo_Ext"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listOfAabrBankmailCalendarIoExt"
})
@XmlRootElement(name = "BankmailPlus_1_Input")
public class BankmailPlus1Input {

    @XmlElement(name = "ListOfAabrBankmailCalendarIo_Ext", namespace = "http://www.siebel.com/xml/AABR%20Bankmail%20Calendar%20IO_Ext", required = true)
    protected ListOfAabrBankmailCalendarIoExt listOfAabrBankmailCalendarIoExt;

    /**
     * Gets the value of the listOfAabrBankmailCalendarIoExt property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfAabrBankmailCalendarIoExt }
     *     
     */
    public ListOfAabrBankmailCalendarIoExt getListOfAabrBankmailCalendarIoExt() {
        return listOfAabrBankmailCalendarIoExt;
    }

    /**
     * Sets the value of the listOfAabrBankmailCalendarIoExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfAabrBankmailCalendarIoExt }
     *     
     */
    public void setListOfAabrBankmailCalendarIoExt(ListOfAabrBankmailCalendarIoExt value) {
        this.listOfAabrBankmailCalendarIoExt = value;
    }

}
