//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-09/06/2010 03:32 PM(foreman)-fcs)
//


package com.siebel.customui;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
/**
 * BankmailAccess
 *
 * <PRE>
 * &lt;B&gt;History:&lt;/B&gt;
 * Developer          Date       Change Reason	  Change
 * ------------------ ---------- ----------------- ----------------------------------------------
 * TCS			  	01-11-2012	Initial version	  Release 1.0
 * </PRE>
 *
 * @author
 * @see
 */
@WebService(name = "BankmailAccess", targetNamespace = "http://siebel.com/CustomUI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankmailAccess {


    /**
     * Description Webservice for interacting with siebel CRM
     * @param bankmailPlus1Input
     * @return
     *     returns com.siebel.customui.BankmailPlus1Output
     */
    @WebMethod(operationName = "BankmailPlus_1", action = "document/http://siebel.com/CustomUI:BankmailPlus_1")
    @WebResult(name = "BankmailPlus_1_Output", targetNamespace = "http://siebel.com/CustomUI", partName = "BankmailPlus_1_Output")
    public BankmailPlus1Output bankmailPlus1(
        @WebParam(name = "BankmailPlus_1_Input", targetNamespace = "http://siebel.com/CustomUI", partName = "BankmailPlus_1_Input")
        BankmailPlus1Input bankmailPlus1Input);

}
