//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-09/06/2010 03:32 PM(foreman)-fcs)
//


package com.siebel.customui;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.siebel.customui package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.siebel.customui
     * 
     */
    public ObjectFactory() {
        //empty constructor
    }

    /**
     * Create an instance of {@link BankmailPlus1Input }
     * @return BankmailPlus1Input BankmailPlus1Input
     */
    public BankmailPlus1Input createBankmailPlus1Input() {
        return new BankmailPlus1Input();
    }

    /**
     * Create an instance of {@link BankmailPlus1Output }
     * @return BankmailPlus1Input BankmailPlus1Input
     */
    public BankmailPlus1Output createBankmailPlus1Output() {
        return new BankmailPlus1Output();
    }

}
